export enum FormCreateType {
  SET_DATA_INFO = "SET_DATA_INFO",
  SET_DATA_VARIANT = "SET_DATA_VARIANT",
  SET_DATA_IMAGE = "SET_DATA_IMAGE",
  SET_DATA_DESCRIPTION = "SET_DATA_DESCRIPTION",
  NEXT_STEP = "NEXT_STEP",
  PREV_STEP = "PREV_STEP",
  CLEAR_ALL = "CLEAR_ALL",
}
